### ISSUE TITLE
Project build fails

### ISSUE THREAD

**Issue by olg-chk** [draganstojanov/MyWeather-MVVM#1]
Hello, can't build the project cause of unresolved links in the ApiCall class.
wAPI.java file is missing in repo. It is listed in .gitignore file.
TIA

**Comment by draganstojanov** [comment]
Hi!
Yes, wAPI.java interface is missing. This app using OpenWeatherMap API to get and show weather data. It's free but I don't want to publicly announce account APPID.
I will add wAPI.java to this repo now, but without APPID and city ID. If you want to use it u have to go to https://openweathermap.org/api and sign up and get your own APPID.
Please, be aware this application is DEMO.  Thanks for watching this repo.

**Comment by olg-chk** [comment]
Thanks, I'm learning app development for Android, so was looking for quite
simple apps, mostly with MVVM architecture. I'll try again after getting
personal APPID

вт, 30 апр. 2019 г. в 14:01, Dragan Stojanov <notifications@github.com>:

**Comment by draganstojanov** [comment]
There is a good one:
https://medium.com/@husayn.hakeem/android-by-example-mvvm-data-binding-introduction-part-1-6a7a5f388bf7.
Good luck!
